# Generated by Django 3.2.4 on 2021-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_userdb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
