# Generated by Django 3.2.4 on 2021-06-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_userdb_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='dob',
        ),
    ]
